# Generated by Django 5.1.4 on 2024-12-20 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folio',
            name='image',
            field=models.ImageField(upload_to='app/images/'),
        ),
    ]
